name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release APK
        run: ./gradlew assembleFossRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/foss/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: release.apk
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}

      - name: Upload Mapping File
        uses: actions/upload-artifact@v2
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt
